# Generated by Django 2.2.4 on 2019-08-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_of_fame', '0003_record_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
