# Generated by Django 2.2.4 on 2019-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_of_fame', '0005_record_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
