# Generated by Django 2.2.4 on 2019-08-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_of_fame', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='walk_of_fame.Profile'),
            preserve_default=False,
        ),
    ]
