# Generated by Django 2.2.4 on 2019-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_of_fame', '0007_record_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
